# Generated by Django 5.2.17 on 2026-10-08 15:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                (
                    "date_naissance",
                    models.DateField(
                        blank=True,
                        help_text="Nécessaire si la catégorie dépend de l'âge ou pour reconnaître un mineur.",
                        null=True,
                    ),
                ),
                (
                    "sexe",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculin"), ("F", "Féminin")],
                        default="",
                        max_length=1,
                    ),
                ),
                ("ville", models.CharField(blank=True, max_length=100)),
                (
                    "structure",
                    models.CharField(
                        blank=True, help_text="Structure représentée.", max_length=200
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clients.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "candidat",
                "verbose_name_plural": "candidats",
                "ordering": ["nom", "prenom"],
            },
        ),
        migrations.CreateModel(
            name="Consentement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("representant_nom", models.CharField(max_length=200)),
                (
                    "representant_lien",
                    models.CharField(
                        help_text="Lien avec le candidat.", max_length=100
                    ),
                ),
                ("version_formulaire", models.CharField(max_length=20)),
                ("date_signature", models.DateField()),
                ("consentement_participation", models.BooleanField(default=False)),
                ("consentement_publication_nom", models.BooleanField(default=False)),
                ("consentement_image_voix", models.BooleanField(default=False)),
                ("document", models.FileField(blank=True, upload_to="consentements/")),
                (
                    "statut",
                    models.CharField(
                        choices=[("valide", "Valide"), ("retire", "Retiré")],
                        default="valide",
                        max_length=20,
                    ),
                ),
                ("date_retrait", models.DateField(blank=True, null=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clients.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "consentement",
                "verbose_name_plural": "consentements",
                "ordering": ["participation", "-date_signature"],
            },
        ),
        migrations.CreateModel(
            name="Participation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("numero_candidat", models.PositiveIntegerField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("inscrit", "Inscrit"),
                            ("admis", "Admis à concourir"),
                            ("retire", "Retiré"),
                        ],
                        default="inscrit",
                        max_length=20,
                    ),
                ),
                (
                    "candidat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="participations",
                        to="candidats.candidat",
                    ),
                ),
            ],
            options={
                "verbose_name": "participation",
                "verbose_name_plural": "participations",
                "ordering": ["concours", "numero_candidat"],
            },
        ),
    ]
