# Generated by Django 5.2.17 on 2026-10-08 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidats", "0001_initial"),
        ("clients", "0001_initial"),
        ("concours", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="participation",
            name="categorie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="participations",
                to="concours.categorie",
            ),
        ),
        migrations.AddField(
            model_name="participation",
            name="concours",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="participations",
                to="concours.concours",
            ),
        ),
        migrations.AddField(
            model_name="participation",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(app_label)s_%(class)s_set",
                to="clients.organisation",
            ),
        ),
        migrations.AddField(
            model_name="consentement",
            name="participation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consentements",
                to="candidats.participation",
            ),
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.UniqueConstraint(
                fields=("concours", "numero_candidat"),
                name="participation_numero_unique_par_concours",
            ),
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.UniqueConstraint(
                fields=("candidat", "categorie"),
                name="participation_unique_par_categorie",
            ),
        ),
        migrations.AddConstraint(
            model_name="participation",
            constraint=models.CheckConstraint(
                condition=models.Q(("numero_candidat__gte", 1)),
                name="participation_numero_au_moins_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="consentement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("statut", "valide")),
                fields=("participation",),
                name="consentement_un_seul_valide_par_participation",
            ),
        ),
        migrations.AddConstraint(
            model_name="consentement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("date_retrait__isnull", True), ("statut", "valide")),
                    models.Q(("date_retrait__isnull", False), ("statut", "retire")),
                    _connector="OR",
                ),
                name="consentement_retrait_coherent",
            ),
        ),
    ]
