# Generated by Django 5.2.17 on 2026-10-08 17:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidats", "0002_initial"),
        ("clients", "0001_initial"),
        ("concours", "0001_initial"),
        ("questions", "0002_lot_serie_questiondeserie_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prestation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "rang_passage",
                    models.PositiveIntegerField(
                        help_text="Rang dans l'ordre de passage de la session."
                    ),
                ),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("tire", "Tiré"),
                            ("en_affichage", "En affichage"),
                            ("en_pause", "En pause"),
                            ("en_notation", "En notation"),
                            ("cloturee", "Clôturée"),
                            ("annulee", "Annulée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "epreuve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prestations",
                        to="concours.epreuve",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clients.organisation",
                    ),
                ),
                (
                    "participation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prestations",
                        to="candidats.participation",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prestations",
                        to="concours.session",
                    ),
                ),
            ],
            options={
                "verbose_name": "prestation",
                "verbose_name_plural": "prestations",
                "ordering": ["session", "epreuve", "rang_passage"],
            },
        ),
        migrations.CreateModel(
            name="Tirage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "rang",
                    models.PositiveSmallIntegerField(
                        help_text="1 à T : numéro du tirage pour cette prestation."
                    ),
                ),
                ("id_demande", models.UUIDField(unique=True)),
                (
                    "terminal",
                    models.CharField(
                        blank=True, help_text="Terminal déclencheur.", max_length=100
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("valide", "Valide"), ("annule", "Annulé")],
                        default="valide",
                        max_length=10,
                    ),
                ),
                ("motif_annulation", models.TextField(blank=True)),
                ("annule_le", models.DateTimeField(blank=True, null=True)),
                ("diapositive_affichee", models.BooleanField(default=False)),
                (
                    "annule_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clients.organisation",
                    ),
                ),
                (
                    "prestation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tirages",
                        to="prestations.prestation",
                    ),
                ),
                (
                    "serie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tirages",
                        to="questions.serie",
                    ),
                ),
            ],
            options={
                "verbose_name": "tirage",
                "verbose_name_plural": "tirages",
                "ordering": ["prestation", "rang", "cree_le"],
            },
        ),
        migrations.AddConstraint(
            model_name="prestation",
            constraint=models.UniqueConstraint(
                fields=("participation", "epreuve"),
                name="prestation_unique_par_participation_et_epreuve",
            ),
        ),
        migrations.AddConstraint(
            model_name="prestation",
            constraint=models.UniqueConstraint(
                fields=("session", "epreuve", "rang_passage"),
                name="prestation_rang_unique_par_session_et_epreuve",
            ),
        ),
        migrations.AddConstraint(
            model_name="prestation",
            constraint=models.CheckConstraint(
                condition=models.Q(("rang_passage__gte", 1)),
                name="prestation_rang_au_moins_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="tirage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("statut", "valide")),
                fields=("prestation", "rang"),
                name="tirage_rang_valide_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="tirage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("statut", "valide")),
                fields=("prestation", "serie"),
                name="tirage_serie_valide_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="tirage",
            constraint=models.CheckConstraint(
                condition=models.Q(("rang__gte", 1)), name="tirage_rang_au_moins_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="tirage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("annule_le__isnull", True),
                        ("annule_par__isnull", True),
                        ("motif_annulation", ""),
                        ("statut", "valide"),
                    ),
                    models.Q(
                        ("annule_le__isnull", False),
                        ("annule_par__isnull", False),
                        ("statut", "annule"),
                        models.Q(("motif_annulation", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="tirage_annulation_coherente",
            ),
        ),
    ]
