# Generated by Django 5.2.17 on 2026-10-08 17:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("concours", "0001_initial"),
        ("prestations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TerminalTirage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=100)),
                ("empreinte", models.CharField(max_length=64, unique=True)),
                ("revoque_le", models.DateTimeField(blank=True, null=True)),
                ("derniere_activite", models.DateTimeField(blank=True, null=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clients.organisation",
                    ),
                ),
                (
                    "prestation_appelee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="prestations.prestation",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="terminaux_tirage",
                        to="concours.session",
                    ),
                ),
            ],
            options={
                "verbose_name": "terminal de tirage",
                "verbose_name_plural": "terminaux de tirage",
                "ordering": ["session", "nom"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "nom"),
                        name="terminal_nom_unique_par_session",
                    )
                ],
            },
        ),
    ]
