# Generated by Django 5.2.17 on 2026-10-08 16:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("concours", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("president", "Président du jury"),
                            ("membre", "Membre du jury"),
                        ],
                        default="membre",
                        max_length=20,
                    ),
                ),
                (
                    "competences",
                    models.CharField(
                        blank=True,
                        help_text="Catégories ou disciplines de compétence (information).",
                        max_length=200,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clients.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "juré",
                "verbose_name_plural": "jurés",
                "ordering": ["nom", "prenom"],
            },
        ),
        migrations.CreateModel(
            name="CodeAccesJure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "empreinte",
                    models.CharField(
                        help_text="HMAC-SHA256 du code.", max_length=64, unique=True
                    ),
                ),
                ("valide_du", models.DateTimeField()),
                ("valide_jusqu_au", models.DateTimeField()),
                ("revoque_le", models.DateTimeField(blank=True, null=True)),
                ("derniere_utilisation", models.DateTimeField(blank=True, null=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clients.organisation",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="codes_jures",
                        to="concours.session",
                    ),
                ),
                (
                    "jure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="codes",
                        to="jury.jure",
                    ),
                ),
            ],
            options={
                "verbose_name": "code d'accès de juré",
                "verbose_name_plural": "codes d'accès de jurés",
                "ordering": ["-valide_du"],
            },
        ),
        migrations.CreateModel(
            name="AffectationJury",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "epreuve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="affectations_jury",
                        to="concours.epreuve",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clients.organisation",
                    ),
                ),
                (
                    "jure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="affectations",
                        to="jury.jure",
                    ),
                ),
            ],
            options={
                "verbose_name": "affectation de juré",
                "verbose_name_plural": "affectations de jurés",
            },
        ),
        migrations.AddConstraint(
            model_name="jure",
            constraint=models.UniqueConstraint(
                fields=("organisation", "nom", "prenom"),
                name="jure_nom_prenom_uniques_par_organisation",
            ),
        ),
        migrations.AddConstraint(
            model_name="codeaccesjure",
            constraint=models.CheckConstraint(
                condition=models.Q(("valide_jusqu_au__gt", models.F("valide_du"))),
                name="code_jure_fin_apres_debut",
            ),
        ),
        migrations.AddConstraint(
            model_name="codeaccesjure",
            constraint=models.UniqueConstraint(
                condition=models.Q(("revoque_le__isnull", True)),
                fields=("jure", "session"),
                name="code_jure_un_seul_actif",
            ),
        ),
        migrations.AddConstraint(
            model_name="affectationjury",
            constraint=models.UniqueConstraint(
                fields=("jure", "epreuve"), name="affectation_jury_unique"
            ),
        ),
    ]
