# Generated by Django 5.2.17 on 2026-10-08 18:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("concours", "0001_initial"),
        ("jury", "0002_evaluation_correctionnote_note_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnexionJure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("empreinte", models.CharField(max_length=64, unique=True)),
                ("valide_jusqu_au", models.DateTimeField()),
                ("revoque_le", models.DateTimeField(blank=True, null=True)),
                ("derniere_activite", models.DateTimeField(blank=True, null=True)),
                ("adresse", models.CharField(blank=True, max_length=64)),
                (
                    "acces",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="connexions",
                        to="jury.codeaccesjure",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clients.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "connexion de juré",
                "verbose_name_plural": "connexions de jurés",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="TentativeCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("adresse", models.CharField(max_length=64)),
                ("reussie", models.BooleanField()),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clients.organisation",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="concours.session",
                    ),
                ),
            ],
            options={
                "verbose_name": "tentative de code",
                "verbose_name_plural": "tentatives de code",
                "indexes": [
                    models.Index(
                        fields=["adresse", "cree_le"],
                        name="jury_tentat_adresse_d35211_idx",
                    )
                ],
            },
        ),
    ]
