# Generated by Django 5.2.17 on 2026-10-08 17:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("coran", "0003_verset"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("passage_coranique", "Passage coranique"),
                            ("enonce", "Énoncé"),
                        ],
                        max_length=20,
                    ),
                ),
                ("enonce", models.TextField(blank=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clients.organisation",
                    ),
                ),
                (
                    "version_corpus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="coran.versioncorpus",
                    ),
                ),
            ],
            options={
                "verbose_name": "question",
                "verbose_name_plural": "questions",
                "ordering": ["-cree_le"],
            },
        ),
        migrations.CreateModel(
            name="PassageCoranique",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("sourate_debut", models.PositiveSmallIntegerField()),
                ("verset_debut", models.PositiveSmallIntegerField()),
                ("sourate_fin", models.PositiveSmallIntegerField()),
                ("verset_fin", models.PositiveSmallIntegerField()),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clients.organisation",
                    ),
                ),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="passage",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "passage coranique",
                "verbose_name_plural": "passages coraniques",
            },
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("type", "passage_coranique"), _negated=True),
                    ("version_corpus__isnull", False),
                    _connector="OR",
                ),
                name="question_passage_exige_version_corpus",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("type", "enonce"), _negated=True),
                    models.Q(("enonce", ""), _negated=True),
                    _connector="OR",
                ),
                name="question_enonce_exige_un_texte",
            ),
        ),
        migrations.AddConstraint(
            model_name="passagecoranique",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sourate_debut__gte", 1),
                    ("verset_debut__gte", 1),
                    ("sourate_fin__gte", 1),
                    ("verset_fin__gte", 1),
                ),
                name="passage_numeros_au_moins_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="passagecoranique",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sourate_debut__lt", models.F("sourate_fin")),
                    models.Q(
                        ("sourate_debut", models.F("sourate_fin")),
                        ("verset_debut__lte", models.F("verset_fin")),
                    ),
                    _connector="OR",
                ),
                name="passage_fin_apres_debut",
            ),
        ),
    ]
