# Generated by Django 5.2.17 on 2026-10-08 17:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        ("concours", "0001_initial"),
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "epreuve",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lot",
                        to="concours.epreuve",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clients.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "lot",
                "verbose_name_plural": "lots",
            },
        ),
        migrations.CreateModel(
            name="Serie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("numero", models.PositiveIntegerField()),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="series",
                        to="questions.lot",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clients.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "série",
                "verbose_name_plural": "séries",
                "ordering": ["lot", "numero"],
            },
        ),
        migrations.CreateModel(
            name="QuestionDeSerie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("rang", models.PositiveSmallIntegerField()),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clients.organisation",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appartenances",
                        to="questions.question",
                    ),
                ),
                (
                    "serie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions_ordonnees",
                        to="questions.serie",
                    ),
                ),
            ],
            options={
                "verbose_name": "question de série",
                "verbose_name_plural": "questions de série",
                "ordering": ["serie", "rang"],
            },
        ),
        migrations.AddConstraint(
            model_name="serie",
            constraint=models.UniqueConstraint(
                fields=("lot", "numero"), name="serie_numero_unique_par_lot"
            ),
        ),
        migrations.AddConstraint(
            model_name="serie",
            constraint=models.CheckConstraint(
                condition=models.Q(("numero__gte", 1)), name="serie_numero_au_moins_1"
            ),
        ),
        migrations.AddConstraint(
            model_name="questiondeserie",
            constraint=models.UniqueConstraint(
                fields=("serie", "rang"), name="questiondeserie_rang_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="questiondeserie",
            constraint=models.UniqueConstraint(
                fields=("serie", "question"), name="questiondeserie_question_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="questiondeserie",
            constraint=models.CheckConstraint(
                condition=models.Q(("rang__gte", 1)),
                name="questiondeserie_rang_au_moins_1",
            ),
        ),
    ]
