# Generated by Django 5.2.17 on 2026-10-08 18:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("concours", "0001_initial"),
        ("prestations", "0003_terminal"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommandePresentation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("id_commande", models.UUIDField(unique=True)),
                ("action", models.CharField(max_length=20)),
                (
                    "version_attendue",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("version_apres", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[("appliquee", "Appliquée"), ("rejetee", "Rejetée")],
                        max_length=10,
                    ),
                ),
                ("raison", models.CharField(blank=True, max_length=40)),
                (
                    "auteur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clients.organisation",
                    ),
                ),
                (
                    "prestation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commandes_presentation",
                        to="prestations.prestation",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commandes_presentation",
                        to="concours.session",
                    ),
                ),
            ],
            options={
                "verbose_name": "commande de présentation",
                "verbose_name_plural": "commandes de présentation",
                "ordering": ["cree_le"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("raison", ""), ("statut", "appliquee")),
                            models.Q(
                                ("statut", "rejetee"),
                                models.Q(("raison", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="commande_raison_si_rejetee",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EtatPresentation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                (
                    "active",
                    models.BooleanField(
                        default=False,
                        help_text="La présentation suivie par les écrans de la session (D41).",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("preparee", "Préparée"),
                            ("affichage", "En affichage"),
                            ("pause", "En pause"),
                            ("terminee", "Terminée"),
                        ],
                        default="preparee",
                        max_length=10,
                    ),
                ),
                (
                    "index",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Diapositive courante (0 = la première).",
                        null=True,
                    ),
                ),
                (
                    "rejeu",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Incrémenté par « Réafficher la diapositive ».",
                    ),
                ),
                ("plan", models.JSONField(default=list)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clients.organisation",
                    ),
                ),
                (
                    "prestation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="presentation",
                        to="prestations.prestation",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="presentations",
                        to="concours.session",
                    ),
                ),
            ],
            options={
                "verbose_name": "état de présentation",
                "verbose_name_plural": "états de présentation",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("active", True)),
                        fields=("session",),
                        name="presentation_une_active_par_session",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="presentation_version_au_moins_1",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("index__isnull", True), ("phase", "preparee")),
                            models.Q(
                                models.Q(("phase", "preparee"), _negated=True),
                                ("index__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="presentation_index_selon_la_phase",
                    ),
                ],
            },
        ),
    ]
