# Generated by Django 5.2.17 on 2026-10-09 12:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utilisateurs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TentativeConnexion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("identifiant", models.CharField(max_length=150)),
                ("adresse", models.CharField(blank=True, max_length=64)),
                ("reussie", models.BooleanField()),
            ],
            options={
                "verbose_name": "tentative de connexion",
                "verbose_name_plural": "tentatives de connexion",
                "indexes": [
                    models.Index(
                        fields=["identifiant", "cree_le"],
                        name="utilisateur_identif_1e9b36_idx",
                    ),
                    models.Index(
                        fields=["adresse", "cree_le"],
                        name="utilisateur_adresse_73ebec_idx",
                    ),
                ],
            },
        ),
    ]
