# Generated by Django 5.2.17 on 2026-10-08 19:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidats", "0002_initial"),
        ("clients", "0001_initial"),
        ("concours", "0002_epreuve_critere_prioritaire"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Classement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("est_correction", models.BooleanField(default=False)),
                ("motif_correction", models.TextField(blank=True)),
                ("valide_le", models.DateTimeField()),
                ("regle_classement", models.CharField(max_length=20)),
                ("regle_departage", models.CharField(blank=True, max_length=30)),
                ("empreinte", models.CharField(max_length=64)),
                (
                    "epreuve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classements",
                        to="concours.epreuve",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clients.organisation",
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "classement définitif",
                "verbose_name_plural": "classements définitifs",
                "ordering": ["epreuve", "version"],
            },
        ),
        migrations.CreateModel(
            name="LigneDeClassement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("rang", models.PositiveIntegerField(blank=True, null=True)),
                ("ex_aequo", models.BooleanField(default=False)),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=9, null=True
                    ),
                ),
                ("complet", models.BooleanField(default=True)),
                ("evaluations_validees", models.PositiveSmallIntegerField(default=0)),
                ("evaluations_attendues", models.PositiveSmallIntegerField(default=0)),
                (
                    "classement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lignes",
                        to="resultats.classement",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clients.organisation",
                    ),
                ),
                (
                    "participation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="candidats.participation",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de classement",
                "verbose_name_plural": "lignes de classement",
                "ordering": ["classement", "rang", "participation__numero_candidat"],
            },
        ),
        migrations.AddConstraint(
            model_name="classement",
            constraint=models.UniqueConstraint(
                fields=("epreuve", "version"),
                name="classement_version_unique_par_epreuve",
            ),
        ),
        migrations.AddConstraint(
            model_name="classement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("est_correction", False),
                        ("motif_correction", ""),
                        ("version", 1),
                    ),
                    models.Q(
                        ("est_correction", True),
                        ("version__gt", 1),
                        models.Q(("motif_correction", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="classement_correction_motivee",
            ),
        ),
        migrations.AddConstraint(
            model_name="lignedeclassement",
            constraint=models.UniqueConstraint(
                fields=("classement", "participation"),
                name="ligne_unique_par_classement",
            ),
        ),
    ]
