# Generated by Django 5.2.17 on 2026-10-08 15:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("coran", "0003_verset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Concours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=200)),
                (
                    "edition",
                    models.CharField(
                        blank=True,
                        help_text="Millésime ou numéro d'édition.",
                        max_length=50,
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("presentiel", "Présentiel")],
                        default="presentiel",
                        max_length=20,
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("ouvert", "Ouvert"),
                            ("en_cours", "En cours"),
                            ("suspendu", "Suspendu"),
                            ("termine", "Terminé"),
                            ("archive", "Archivé"),
                        ],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                (
                    "configuration_validee_le",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "configuration_empreinte",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Empreinte SHA-256 de la configuration au moment de sa validation.",
                        max_length=64,
                    ),
                ),
                (
                    "configuration_validee_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="concours",
                        to="clients.mission",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clients.organisation",
                    ),
                ),
                (
                    "version_corpus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="concours",
                        to="coran.versioncorpus",
                    ),
                ),
            ],
            options={
                "verbose_name": "concours",
                "verbose_name_plural": "concours",
                "ordering": ["-date_debut", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=100)),
                (
                    "discipline",
                    models.CharField(
                        choices=[
                            ("memorisation", "Mémorisation"),
                            ("tajwid", "Tajwid"),
                            ("tilawa", "Tilawa"),
                            ("questions", "Questions"),
                            ("personnalisee", "Personnalisée"),
                        ],
                        default="memorisation",
                        max_length=20,
                    ),
                ),
                (
                    "age_minimum",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "age_maximum",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("effectif_prevu", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "regle_classement",
                    models.CharField(
                        choices=[
                            ("moyenne", "Moyenne"),
                            ("total", "Total"),
                            ("elimination", "Élimination"),
                        ],
                        default="moyenne",
                        max_length=20,
                    ),
                ),
                (
                    "regle_departage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("moyenne_generale", "Moyenne générale"),
                            ("critere_prioritaire", "Critère prioritaire"),
                            ("epreuve_supplementaire", "Épreuve supplémentaire"),
                            ("decision_comite", "Décision documentée du comité"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clients.organisation",
                    ),
                ),
                (
                    "concours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categories",
                        to="concours.concours",
                    ),
                ),
            ],
            options={
                "verbose_name": "catégorie",
                "verbose_name_plural": "catégories",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Epreuve",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=100)),
                ("ordre", models.PositiveSmallIntegerField()),
                (
                    "questions_par_serie",
                    models.PositiveSmallIntegerField(help_text="P"),
                ),
                (
                    "tirages_par_candidat",
                    models.PositiveSmallIntegerField(default=1, help_text="T"),
                ),
                ("reutilisation_autre_candidat", models.BooleanField(default=False)),
                (
                    "reutilisation_meme_candidat_autre_epreuve",
                    models.BooleanField(default=False),
                ),
                ("exclusion_definitive", models.BooleanField(default=True)),
                (
                    "mode_affichage",
                    models.CharField(
                        choices=[
                            ("arabe_seul", "Arabe seul"),
                            ("arabe_et_traduction", "Arabe avec traduction française"),
                        ],
                        default="arabe_seul",
                        max_length=30,
                    ),
                ),
                ("affichage_scene", models.BooleanField(default=False)),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("en_preparation", "En préparation"),
                            ("ouverte", "Ouverte"),
                            ("terminee", "Terminée"),
                        ],
                        default="en_preparation",
                        max_length=20,
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="epreuves",
                        to="concours.categorie",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clients.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "épreuve",
                "verbose_name_plural": "épreuves",
                "ordering": ["categorie", "ordre"],
            },
        ),
        migrations.CreateModel(
            name="CritereNotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("libelle", models.CharField(max_length=100)),
                ("ordre", models.PositiveSmallIntegerField()),
                ("maximum", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "coefficient",
                    models.DecimalField(decimal_places=2, default=1, max_digits=5),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clients.organisation",
                    ),
                ),
                (
                    "epreuve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="criteres",
                        to="concours.epreuve",
                    ),
                ),
            ],
            options={
                "verbose_name": "critère de notation",
                "verbose_name_plural": "critères de notation",
                "ordering": ["epreuve", "ordre"],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("lieu", models.CharField(blank=True, max_length=200)),
                ("serveur_de_salle", models.CharField(blank=True, max_length=100)),
                (
                    "concours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="concours.concours",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clients.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "session",
                "verbose_name_plural": "sessions",
                "ordering": ["date", "nom"],
            },
        ),
        migrations.AddConstraint(
            model_name="concours",
            constraint=models.UniqueConstraint(
                fields=("organisation", "nom", "edition"),
                name="concours_nom_edition_uniques",
            ),
        ),
        migrations.AddConstraint(
            model_name="concours",
            constraint=models.CheckConstraint(
                condition=models.Q(("date_fin__gte", models.F("date_debut"))),
                name="concours_date_fin_apres_date_debut",
            ),
        ),
        migrations.AddConstraint(
            model_name="concours",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("configuration_empreinte", ""),
                        ("configuration_validee_le__isnull", True),
                        ("configuration_validee_par__isnull", True),
                    ),
                    models.Q(
                        ("configuration_validee_le__isnull", False),
                        ("configuration_validee_par__isnull", False),
                        models.Q(("configuration_empreinte", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="concours_validation_configuration_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="concours",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("etat", "brouillon"),
                    models.Q(
                        ("version_corpus__isnull", False),
                        ("configuration_validee_le__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="concours_ouvert_exige_corpus_et_validation",
            ),
        ),
        migrations.AddConstraint(
            model_name="categorie",
            constraint=models.UniqueConstraint(
                fields=("concours", "nom"), name="categorie_nom_unique_par_concours"
            ),
        ),
        migrations.AddConstraint(
            model_name="categorie",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("age_minimum__isnull", True),
                    ("age_maximum__isnull", True),
                    ("age_maximum__gte", models.F("age_minimum")),
                    _connector="OR",
                ),
                name="categorie_age_maximum_apres_age_minimum",
            ),
        ),
        migrations.AddConstraint(
            model_name="epreuve",
            constraint=models.UniqueConstraint(
                fields=("categorie", "ordre"), name="epreuve_ordre_unique_par_categorie"
            ),
        ),
        migrations.AddConstraint(
            model_name="epreuve",
            constraint=models.UniqueConstraint(
                fields=("categorie", "nom"), name="epreuve_nom_unique_par_categorie"
            ),
        ),
        migrations.AddConstraint(
            model_name="epreuve",
            constraint=models.CheckConstraint(
                condition=models.Q(("questions_par_serie__gte", 1)),
                name="epreuve_p_au_moins_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="epreuve",
            constraint=models.CheckConstraint(
                condition=models.Q(("tirages_par_candidat__gte", 1)),
                name="epreuve_t_au_moins_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="criterenotation",
            constraint=models.UniqueConstraint(
                fields=("epreuve", "ordre"), name="critere_ordre_unique_par_epreuve"
            ),
        ),
        migrations.AddConstraint(
            model_name="criterenotation",
            constraint=models.UniqueConstraint(
                fields=("epreuve", "libelle"), name="critere_libelle_unique_par_epreuve"
            ),
        ),
        migrations.AddConstraint(
            model_name="criterenotation",
            constraint=models.CheckConstraint(
                condition=models.Q(("maximum__gt", 0)), name="critere_maximum_positif"
            ),
        ),
        migrations.AddConstraint(
            model_name="criterenotation",
            constraint=models.CheckConstraint(
                condition=models.Q(("coefficient__gt", 0)),
                name="critere_coefficient_positif",
            ),
        ),
        migrations.AddConstraint(
            model_name="session",
            constraint=models.UniqueConstraint(
                fields=("concours", "nom"), name="session_nom_unique_par_concours"
            ),
        ),
    ]
