# Generated by Django 5.2.17 on 2026-10-08 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concours", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="epreuve",
            name="critere_prioritaire",
            field=models.ForeignKey(
                blank=True,
                help_text="Critère qui départage les égalités si la catégorie le prévoit.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="concours.criterenotation",
            ),
        ),
    ]
