# Generated by Django 5.2.17 on 2026-10-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VersionCorpus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(default="Tanzil", max_length=100)),
                (
                    "version_source",
                    models.CharField(
                        help_text="Version indiquée dans l'en-tête du fichier Tanzil.",
                        max_length=50,
                    ),
                ),
                (
                    "riwaya",
                    models.CharField(
                        choices=[("hafs", "Hafs ʿan ʿĀṣim")],
                        default="hafs",
                        max_length=20,
                    ),
                ),
                ("nom_fichier", models.CharField(max_length=255)),
                (
                    "empreinte_sha256",
                    models.CharField(
                        help_text="Empreinte SHA-256 du fichier source (64 caractères hexadécimaux).",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("date_import", models.DateTimeField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("importee", "Importée"),
                            ("validee", "Validée"),
                            ("active", "Active"),
                            ("retiree", "Retirée"),
                        ],
                        default="importee",
                        max_length=20,
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date du procès-verbal de validation du référent coranique.",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "version du corpus",
                "verbose_name_plural": "versions du corpus",
                "ordering": ["-date_import"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("statut", "active")),
                        fields=("riwaya",),
                        name="une_seule_version_active_par_riwaya",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("empreinte_sha256__regex", "^[0-9a-f]{64}$")
                        ),
                        name="empreinte_sha256_valide",
                    ),
                ],
            },
        ),
    ]
