# Generated by Django 5.2.17 on 2026-10-08 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coran", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sourate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveSmallIntegerField(help_text="Numéro de 1 à 114."),
                ),
                ("nom_arabe", models.CharField(max_length=100)),
                (
                    "nom_translitteration",
                    models.CharField(
                        help_text="Translittération de Tanzil (la forme française usuelle sera validée par le référent).",
                        max_length=100,
                    ),
                ),
                (
                    "nombre_versets",
                    models.PositiveSmallIntegerField(
                        help_text="Nombre de versets déclaré par les métadonnées Tanzil."
                    ),
                ),
                (
                    "type_revelation",
                    models.CharField(
                        choices=[
                            ("mecquoise", "Mecquoise"),
                            ("medinoise", "Médinoise"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "ordre_revelation",
                    models.PositiveSmallIntegerField(
                        help_text="Rang dans l'ordre de révélation, de 1 à 114."
                    ),
                ),
                (
                    "basmala",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Basmala de tête, reprise telle quelle de l'attribut « bismillah » du verset 1. Vide pour les sourates 1 et 9 (§12.4).",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sourates",
                        to="coran.versioncorpus",
                    ),
                ),
            ],
            options={
                "verbose_name": "sourate",
                "verbose_name_plural": "sourates",
                "ordering": ["version", "numero"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("version", "numero"),
                        name="sourate_numero_unique_par_version",
                    ),
                    models.UniqueConstraint(
                        fields=("version", "ordre_revelation"),
                        name="sourate_ordre_revelation_unique_par_version",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("numero__range", (1, 114))),
                        name="sourate_numero_entre_1_et_114",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ordre_revelation__range", (1, 114))),
                        name="sourate_ordre_revelation_entre_1_et_114",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("nombre_versets__gte", 1)),
                        name="sourate_au_moins_un_verset",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("numero__in", [1, 9]), _negated=True),
                            ("basmala", ""),
                            _connector="OR",
                        ),
                        name="sourates_1_et_9_sans_basmala",
                    ),
                ],
            },
        ),
    ]
