# Generated by Django 5.2.17 on 2026-10-08 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coran", "0002_sourate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Verset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveSmallIntegerField(
                        help_text="Numéro du verset dans sa sourate, à partir de 1."
                    ),
                ),
                (
                    "texte",
                    models.TextField(
                        help_text="Texte exact du verset, repris du fichier Tanzil sans aucune transformation."
                    ),
                ),
                (
                    "sourate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="versets",
                        to="coran.sourate",
                    ),
                ),
            ],
            options={
                "verbose_name": "verset",
                "verbose_name_plural": "versets",
                "ordering": ["sourate__numero", "numero"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sourate", "numero"),
                        name="verset_numero_unique_par_sourate",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("numero__gte", 1)),
                        name="verset_numero_au_moins_1",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("texte__regex", "\\S")),
                        name="verset_texte_non_vide",
                    ),
                ],
            },
        ),
    ]
