# Generated by Django 5.2.17 on 2026-10-09 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coran", "0003_verset"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidationCorpus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("referent_nom", models.CharField(max_length=200)),
                ("referent_qualite", models.CharField(blank=True, max_length=200)),
                (
                    "date_signature",
                    models.DateField(
                        help_text="Date de signature du procès-verbal par le référent coranique."
                    ),
                ),
                ("validee_le", models.DateTimeField(auto_now_add=True)),
                (
                    "controles",
                    models.JSONField(
                        help_text="Résultat de chaque contrôle automatique au moment de la validation."
                    ),
                ),
                (
                    "empreinte_echantillon",
                    models.CharField(
                        help_text="Empreinte de l'échantillon de relecture signé (version + références), pour le retrouver à l'identique.",
                        max_length=64,
                    ),
                ),
                (
                    "validee_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="validation",
                        to="coran.versioncorpus",
                    ),
                ),
            ],
            options={
                "verbose_name": "validation du corpus",
                "verbose_name_plural": "validations du corpus",
            },
        ),
    ]
