# Generated by Django 5.2.17 on 2026-10-08 18:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChaineAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dernier_numero", models.PositiveIntegerField(default=0)),
                (
                    "derniere_empreinte",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        help_text="Vide pour la chaîne « système ».",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="clients.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "chaîne d'audit",
                "verbose_name_plural": "chaînes d'audit",
            },
        ),
        migrations.CreateModel(
            name="EntreeAudit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                ("horodatage", models.DateTimeField()),
                ("auteur_libelle", models.CharField(blank=True, max_length=200)),
                ("action", models.CharField(max_length=60)),
                ("objet_type", models.CharField(blank=True, max_length=60)),
                ("objet_id", models.CharField(blank=True, max_length=64)),
                ("terminal", models.CharField(blank=True, max_length=100)),
                ("details", models.JSONField(default=dict)),
                ("empreinte_precedente", models.CharField(blank=True, max_length=64)),
                ("empreinte", models.CharField(max_length=64)),
                (
                    "auteur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "chaine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entrees",
                        to="audit.chaineaudit",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entrees_audit",
                        to="clients.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "entrée d'audit",
                "verbose_name_plural": "entrées d'audit",
                "ordering": ["chaine", "numero"],
            },
        ),
        migrations.AddConstraint(
            model_name="chaineaudit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organisation__isnull", False)),
                fields=("organisation",),
                name="chaine_une_par_organisation",
            ),
        ),
        migrations.AddConstraint(
            model_name="chaineaudit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("organisation__isnull", True)),
                fields=("organisation",),
                name="chaine_systeme_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="entreeaudit",
            index=models.Index(
                fields=["organisation", "action"], name="audit_entre_organis_58be32_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="entreeaudit",
            index=models.Index(
                fields=["objet_type", "objet_id"], name="audit_entre_objet_t_96ea57_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="entreeaudit",
            constraint=models.UniqueConstraint(
                fields=("chaine", "numero"), name="audit_numero_unique_par_chaine"
            ),
        ),
        migrations.AddConstraint(
            model_name="entreeaudit",
            constraint=models.UniqueConstraint(
                fields=("empreinte",), name="audit_empreinte_unique"
            ),
        ),
    ]
