# Generated by Django 5.2.17 on 2026-10-08 15:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=200, unique=True)),
                ("logo", models.FileField(blank=True, upload_to="logos/")),
                (
                    "couleur_principale",
                    models.CharField(blank=True, default="", max_length=7),
                ),
                (
                    "couleur_secondaire",
                    models.CharField(blank=True, default="", max_length=7),
                ),
                ("adresse", models.TextField(blank=True)),
                ("telephone", models.CharField(blank=True, max_length=50)),
                ("courriel", models.EmailField(blank=True, max_length=254)),
                (
                    "statut",
                    models.CharField(
                        choices=[("actif", "Actif"), ("archive", "Archivé")],
                        default="actif",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "organisation",
                "verbose_name_plural": "organisations",
                "ordering": ["nom"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("couleur_principale__regex", "^(#[0-9A-Fa-f]{6})?$")
                        ),
                        name="organisation_couleur_principale_valide",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("couleur_secondaire__regex", "^(#[0-9A-Fa-f]{6})?$")
                        ),
                        name="organisation_couleur_secondaire_valide",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                ("modifie_le", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=200)),
                ("lieu", models.CharField(max_length=200)),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField()),
                (
                    "formule",
                    models.CharField(
                        blank=True,
                        help_text="Formule commerciale retenue.",
                        max_length=100,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_preparation", "En préparation"),
                            ("en_cours", "En cours"),
                            ("terminee", "Terminée"),
                            ("archivee", "Archivée"),
                        ],
                        default="en_preparation",
                        max_length=20,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_set",
                        to="clients.organisation",
                    ),
                ),
            ],
            options={
                "verbose_name": "mission",
                "verbose_name_plural": "missions",
                "ordering": ["-date_debut"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("date_fin__gte", models.F("date_debut"))),
                        name="mission_date_fin_apres_date_debut",
                    )
                ],
            },
        ),
    ]
